rule index_genomes:
    input:
        "data/genome/genome{genome_num}/sequence.fasta"
    output:
        "data/genome/genome{genome_num}/sequence.fasta.amb"
    shell:
        """
        bwa index {input}
        """

rule align_reads:
    input:
        genome="data/genome/genome{genome_num}/sequence.fasta",
        read="data/gene/{accession}.fastq.gz"
    output:
        "data/mapped_reads/align_g{genome_num}_{accession}.bam"
    shell:
        "bwa mem {input.genome} {input.read} | samtools view -Sb - > data/mapped_reads/{output}"