rule test_transform:
    input:
        "data/input_{sample}.csv"
    output:
        "data/output_{sample}.csv"
    shell:
        "\"C:/Program Files/R/R-4.4.1/bin/Rscript.exe\" test_transform.R {input} {output}"
